### ISSUE TITLE
Not Really an issue but could you please release the updater source code

### ISSUE THREAD

**Issue by Directory** [ThomHPL/BaseI6_updater#2]
I would love to learn from it. also i would like to patch a bug that is not your fault. its a me thing

**Comment by ThomHPL** [comment]
Hi!
Not sure I understand your request, the code is already on github (see https://github.com/ThomHPL/BaseI6_updater/tree/master/src).

**Comment by Gabrieldaboss65** [comment]
im retarded sorry
